name: Text Extraction Analysis CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: ta_env
          auto-update-conda: true

      - name: Create folders
        run: |
          mkdir -p data/pdf data/tei results

      - name: Run main pipeline
        shell: bash -l {0}
        run: |
          conda activate ta_env
          python scripts/run_pipeline.py

      - name: Run tests
        shell: bash -l {0}
        run: | 
            conda activate ta_env
            python -m unittest discover test


        
